[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && node dist/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
