export {
  NATIVE_MON_ADDRESS,
  WMON_ADDRESS,
  MONAD_CHAIN_ID,
  MONAD_RPC_URL,
  MONAD_BLOCK_EXPLORER,
  KURU_CONTRACTS,
  DEFAULT_SLIPPAGE_OPTIONS,
  QUOTE_REFRESH_INTERVAL_MS,
  PLATFORM_FEE_BPS,
  API_ENDPOINTS,
} from '@shared/constants';
